### ISSUE TITLE
Re: 'Get data'

### ISSUE THREAD

**Issue by nmtoken** [alphagov/datagovuk-tech-docs#122]
Problem with 'Get data' (guidance.data.gov.uk/get_data/)

Couldn't see a page to comment directly on the API, so assume this is closest proxy..

The CSW API configuration is malformed, preventing software from being able to harvest any metadata :(

Looking at say the response for the following request: https://ckan.publishing.service.gov.uk/csw?SERVICE=CSW&request=GetCapabilities&version=2.0.2  or the default https://ckan.publishing.service.gov.uk/csw response

The use of  `${CKAN_SITE_URL}/` is an issue as software parsers cannot resolve the variable.  Should be instead:
`https://ckan.publishing.service.gov.uk`

**Comment by PeterParslow** [comment]
I have had good response by reporting issues at https://govuk.zendesk.com/ - my issues where with their CSW harvest of my server: recently resolved (again).

**Comment by nmtoken** [comment]
Trying to code around this issue, but now discover that it's not possible to retrieve any ISO XML record by ID, trying against `version=2.0.2` and `version=3.0.0`  for example:

    https://ckan.publishing.service.gov.uk/csw?SERVICE=CSW&request=GetRecordById&version=3.0.0&ElementSetName=full&id=3946906d-fb54-46f5-a7fe-259ab4d89946&

gives just:

    
    <csw30:Record xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:csw30="http://www.opengis.net/cat/csw/3.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gml="http://www.opengis.net/gml" xmlns:ows="http://www.opengis.net/ows" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <dc:identifier>3946906d-fb54-46f5-a7fe-259ab4d89946</dc:identifier>
    <dc:title/>
    <dc:type/>
    </csw30:Record>

    https://ckan.publishing.service.gov.uk/csw?SERVICE=CSW&request=GetRecordById&version=3.0.0&ElementSetName=full&id=3946906d-fb54-46f5-a7fe-259ab4d89946&outputSchema=http://www.isotc211.org/2005/gmd&

Gives  **Internal Server Error**

    https://ckan.publishing.service.gov.uk/csw?SERVICE=CSW&request=GetRecordById&version=3.0.0&ElementSetName=full&id=3946906d-fb54-46f5-a7fe-259ab4d89946&outputSchema=http://www.w3.org/2005/Atom

Gives:  

     
    <atom:entry xmlns:atom="http://www.w3.org/2005/Atom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2005/Atom http://www.kbcafe.com/rss/atom.xsd.xml">
    <atom:id>3946906d-fb54-46f5-a7fe-259ab4d89946</atom:id>
    <dc:identifier xmlns:dc="http://purl.org/dc/elements/1.1/">3946906d-fb54-46f5-a7fe-259ab4d89946</dc:identifier>
    <atom:link href="${CKAN_SITE_URL}/csw?service=CSW&version=2.0.2&request=GetRepositoryItem&id=3946906d-fb54-46f5-a7fe-259ab4d89946"/>
    <atom:title/>
    <atom:updated>2023-09-20T10:26:43Z</atom:updated>
    </atom:entry>

but the link  (`https://ckan.publishing.service.gov.uk/csw?service=CSW&version=2.0.2&request=GetRepositoryItem&id=3946906d-fb54-46f5-a7fe-259ab4d89946`)  gives: **Internal Server Error**


Where `3946906d-fb54-46f5-a7fe-259ab4d89946` is an identifier returned in a GetRecords request like:

    https://ckan.publishing.service.gov.uk/csw?SERVICE=CSW&request=GetRecords&version=3.0.0&ElementSetName=summary&typeNames=gmd:MD_Metadata&resultType=results

**Comment by deborahchua** [comment]
Hi @nmtoken, we have pushed a fix and it should no longer be an issue 👍

**Comment by kentsanggds** [comment]
Issue will be closed here as not the correct repo to report this.
