### ISSUE TITLE
Something in https://guidance.data.gov.uk/publish_and_manage_data/ should reference the map preview info from the developer docs

### ISSUE THREAD

**Issue by archaeogeek** [alphagov/datagovuk-tech-docs#41]
The documentation for users on publishing and harvesting spatial/gemini/location metadata should contain guidance on the "preview on maps" link and in what situations it works. This should include:

- the fact that the preview will only trigger for WMS URLs
- the fact that it will only work for service records and not for datasets
- the fact that it will only work for WMS version 1.3.0.

I don't think you should expect end-users to find the information hidden in the developer documentation.

**Comment by kentsanggds** [comment]
Some guidance now available - https://guidance.data.gov.uk/publish_and_manage_data/harvest_or_add_data/inspire/#map-preview
